#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BD_BoleteriaCine")]
	public partial class BD_CineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttbl_Bebida(tbl_Bebida instance);
    partial void Updatetbl_Bebida(tbl_Bebida instance);
    partial void Deletetbl_Bebida(tbl_Bebida instance);
    partial void Inserttbl_Usuario(tbl_Usuario instance);
    partial void Updatetbl_Usuario(tbl_Usuario instance);
    partial void Deletetbl_Usuario(tbl_Usuario instance);
    partial void Inserttbl_Combo(tbl_Combo instance);
    partial void Updatetbl_Combo(tbl_Combo instance);
    partial void Deletetbl_Combo(tbl_Combo instance);
    partial void Inserttbl_Factura(tbl_Factura instance);
    partial void Updatetbl_Factura(tbl_Factura instance);
    partial void Deletetbl_Factura(tbl_Factura instance);
    partial void Inserttbl_Funcion(tbl_Funcion instance);
    partial void Updatetbl_Funcion(tbl_Funcion instance);
    partial void Deletetbl_Funcion(tbl_Funcion instance);
    partial void Inserttbl_Genero(tbl_Genero instance);
    partial void Updatetbl_Genero(tbl_Genero instance);
    partial void Deletetbl_Genero(tbl_Genero instance);
    partial void Inserttbl_Hora(tbl_Hora instance);
    partial void Updatetbl_Hora(tbl_Hora instance);
    partial void Deletetbl_Hora(tbl_Hora instance);
    partial void Inserttbl_Pelicula(tbl_Pelicula instance);
    partial void Updatetbl_Pelicula(tbl_Pelicula instance);
    partial void Deletetbl_Pelicula(tbl_Pelicula instance);
    partial void Inserttbl_Persona(tbl_Persona instance);
    partial void Updatetbl_Persona(tbl_Persona instance);
    partial void Deletetbl_Persona(tbl_Persona instance);
    partial void Inserttbl_Rol(tbl_Rol instance);
    partial void Updatetbl_Rol(tbl_Rol instance);
    partial void Deletetbl_Rol(tbl_Rol instance);
    partial void Inserttbl_Sala(tbl_Sala instance);
    partial void Updatetbl_Sala(tbl_Sala instance);
    partial void Deletetbl_Sala(tbl_Sala instance);
    partial void Inserttbl_Sanck(tbl_Sanck instance);
    partial void Updatetbl_Sanck(tbl_Sanck instance);
    partial void Deletetbl_Sanck(tbl_Sanck instance);
    #endregion
		
		public BD_CineDataContext() : 
				base(global::Capa_Datos.Properties.Settings.Default.BD_BoleteriaCineConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BD_CineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_CineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_CineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BD_CineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_Bebida> tbl_Bebida
		{
			get
			{
				return this.GetTable<tbl_Bebida>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Usuario> tbl_Usuario
		{
			get
			{
				return this.GetTable<tbl_Usuario>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Combo> tbl_Combo
		{
			get
			{
				return this.GetTable<tbl_Combo>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Factura> tbl_Factura
		{
			get
			{
				return this.GetTable<tbl_Factura>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Funcion> tbl_Funcion
		{
			get
			{
				return this.GetTable<tbl_Funcion>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Genero> tbl_Genero
		{
			get
			{
				return this.GetTable<tbl_Genero>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Hora> tbl_Hora
		{
			get
			{
				return this.GetTable<tbl_Hora>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Pelicula> tbl_Pelicula
		{
			get
			{
				return this.GetTable<tbl_Pelicula>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Persona> tbl_Persona
		{
			get
			{
				return this.GetTable<tbl_Persona>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Rol> tbl_Rol
		{
			get
			{
				return this.GetTable<tbl_Rol>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Sala> tbl_Sala
		{
			get
			{
				return this.GetTable<tbl_Sala>();
			}
		}
		
		public System.Data.Linq.Table<tbl_Sanck> tbl_Sanck
		{
			get
			{
				return this.GetTable<tbl_Sanck>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Bebida")]
	public partial class tbl_Bebida : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _beb_id;
		
		private string _beb_nombre;
		
		private System.Nullable<float> _beb_precio;
		
		private System.Nullable<int> _beb_stock;
		
		private System.Data.Linq.Binary _beb_img;
		
		private System.Nullable<char> _beb_estado;
		
		private EntitySet<tbl_Combo> _tbl_Combo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbeb_idChanging(int value);
    partial void Onbeb_idChanged();
    partial void Onbeb_nombreChanging(string value);
    partial void Onbeb_nombreChanged();
    partial void Onbeb_precioChanging(System.Nullable<float> value);
    partial void Onbeb_precioChanged();
    partial void Onbeb_stockChanging(System.Nullable<int> value);
    partial void Onbeb_stockChanged();
    partial void Onbeb_imgChanging(System.Data.Linq.Binary value);
    partial void Onbeb_imgChanged();
    partial void Onbeb_estadoChanging(System.Nullable<char> value);
    partial void Onbeb_estadoChanged();
    #endregion
		
		public tbl_Bebida()
		{
			this._tbl_Combo = new EntitySet<tbl_Combo>(new Action<tbl_Combo>(this.attach_tbl_Combo), new Action<tbl_Combo>(this.detach_tbl_Combo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int beb_id
		{
			get
			{
				return this._beb_id;
			}
			set
			{
				if ((this._beb_id != value))
				{
					this.Onbeb_idChanging(value);
					this.SendPropertyChanging();
					this._beb_id = value;
					this.SendPropertyChanged("beb_id");
					this.Onbeb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_nombre", DbType="VarChar(100)")]
		public string beb_nombre
		{
			get
			{
				return this._beb_nombre;
			}
			set
			{
				if ((this._beb_nombre != value))
				{
					this.Onbeb_nombreChanging(value);
					this.SendPropertyChanging();
					this._beb_nombre = value;
					this.SendPropertyChanged("beb_nombre");
					this.Onbeb_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_precio", DbType="Real")]
		public System.Nullable<float> beb_precio
		{
			get
			{
				return this._beb_precio;
			}
			set
			{
				if ((this._beb_precio != value))
				{
					this.Onbeb_precioChanging(value);
					this.SendPropertyChanging();
					this._beb_precio = value;
					this.SendPropertyChanged("beb_precio");
					this.Onbeb_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_stock", DbType="Int")]
		public System.Nullable<int> beb_stock
		{
			get
			{
				return this._beb_stock;
			}
			set
			{
				if ((this._beb_stock != value))
				{
					this.Onbeb_stockChanging(value);
					this.SendPropertyChanging();
					this._beb_stock = value;
					this.SendPropertyChanged("beb_stock");
					this.Onbeb_stockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary beb_img
		{
			get
			{
				return this._beb_img;
			}
			set
			{
				if ((this._beb_img != value))
				{
					this.Onbeb_imgChanging(value);
					this.SendPropertyChanging();
					this._beb_img = value;
					this.SendPropertyChanged("beb_img");
					this.Onbeb_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_estado", DbType="Char(1)")]
		public System.Nullable<char> beb_estado
		{
			get
			{
				return this._beb_estado;
			}
			set
			{
				if ((this._beb_estado != value))
				{
					this.Onbeb_estadoChanging(value);
					this.SendPropertyChanging();
					this._beb_estado = value;
					this.SendPropertyChanged("beb_estado");
					this.Onbeb_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Bebida_tbl_Combo", Storage="_tbl_Combo", ThisKey="beb_id", OtherKey="beb_id")]
		public EntitySet<tbl_Combo> tbl_Combo
		{
			get
			{
				return this._tbl_Combo;
			}
			set
			{
				this._tbl_Combo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Combo(tbl_Combo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Bebida = this;
		}
		
		private void detach_tbl_Combo(tbl_Combo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Bebida = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Usuario")]
	public partial class tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private string _usu_usuario;
		
		private string _usu_pass;
		
		private string _usu_email;
		
		private System.Nullable<char> _usu_estado;
		
		private System.Nullable<int> _rol_id;
		
		private System.Nullable<int> _per_id;
		
		private EntityRef<tbl_Persona> _tbl_Persona;
		
		private EntityRef<tbl_Rol> _tbl_Rol;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onusu_usuarioChanging(string value);
    partial void Onusu_usuarioChanged();
    partial void Onusu_passChanging(string value);
    partial void Onusu_passChanged();
    partial void Onusu_emailChanging(string value);
    partial void Onusu_emailChanged();
    partial void Onusu_estadoChanging(System.Nullable<char> value);
    partial void Onusu_estadoChanged();
    partial void Onrol_idChanging(System.Nullable<int> value);
    partial void Onrol_idChanged();
    partial void Onper_idChanging(System.Nullable<int> value);
    partial void Onper_idChanged();
    #endregion
		
		public tbl_Usuario()
		{
			this._tbl_Persona = default(EntityRef<tbl_Persona>);
			this._tbl_Rol = default(EntityRef<tbl_Rol>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_usuario", DbType="VarChar(100)")]
		public string usu_usuario
		{
			get
			{
				return this._usu_usuario;
			}
			set
			{
				if ((this._usu_usuario != value))
				{
					this.Onusu_usuarioChanging(value);
					this.SendPropertyChanging();
					this._usu_usuario = value;
					this.SendPropertyChanged("usu_usuario");
					this.Onusu_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_pass", DbType="VarChar(100)")]
		public string usu_pass
		{
			get
			{
				return this._usu_pass;
			}
			set
			{
				if ((this._usu_pass != value))
				{
					this.Onusu_passChanging(value);
					this.SendPropertyChanging();
					this._usu_pass = value;
					this.SendPropertyChanged("usu_pass");
					this.Onusu_passChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_email", DbType="VarChar(100)")]
		public string usu_email
		{
			get
			{
				return this._usu_email;
			}
			set
			{
				if ((this._usu_email != value))
				{
					this.Onusu_emailChanging(value);
					this.SendPropertyChanging();
					this._usu_email = value;
					this.SendPropertyChanged("usu_email");
					this.Onusu_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="Char(1)")]
		public System.Nullable<char> usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", DbType="Int")]
		public System.Nullable<int> rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					if (this._tbl_Rol.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int")]
		public System.Nullable<int> per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					if (this._tbl_Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Persona_tbl_Usuario", Storage="_tbl_Persona", ThisKey="per_id", OtherKey="per_id", IsForeignKey=true)]
		public tbl_Persona tbl_Persona
		{
			get
			{
				return this._tbl_Persona.Entity;
			}
			set
			{
				tbl_Persona previousValue = this._tbl_Persona.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Persona.Entity = null;
						previousValue.tbl_Usuario.Remove(this);
					}
					this._tbl_Persona.Entity = value;
					if ((value != null))
					{
						value.tbl_Usuario.Add(this);
						this._per_id = value.per_id;
					}
					else
					{
						this._per_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Rol_tbl_Usuario", Storage="_tbl_Rol", ThisKey="rol_id", OtherKey="rol_id", IsForeignKey=true)]
		public tbl_Rol tbl_Rol
		{
			get
			{
				return this._tbl_Rol.Entity;
			}
			set
			{
				tbl_Rol previousValue = this._tbl_Rol.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Rol.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Rol.Entity = null;
						previousValue.tbl_Usuario.Remove(this);
					}
					this._tbl_Rol.Entity = value;
					if ((value != null))
					{
						value.tbl_Usuario.Add(this);
						this._rol_id = value.rol_id;
					}
					else
					{
						this._rol_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Rol");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Combo")]
	public partial class tbl_Combo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _com_id;
		
		private string _com_nombre;
		
		private System.Nullable<float> _com_precio;
		
		private System.Data.Linq.Binary _com_img;
		
		private System.Nullable<int> _beb_id;
		
		private System.Nullable<int> _snac_id;
		
		private System.Nullable<char> _snac_iestado;
		
		private EntitySet<tbl_Factura> _tbl_Factura;
		
		private EntityRef<tbl_Bebida> _tbl_Bebida;
		
		private EntityRef<tbl_Sanck> _tbl_Sanck;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncom_idChanging(int value);
    partial void Oncom_idChanged();
    partial void Oncom_nombreChanging(string value);
    partial void Oncom_nombreChanged();
    partial void Oncom_precioChanging(System.Nullable<float> value);
    partial void Oncom_precioChanged();
    partial void Oncom_imgChanging(System.Data.Linq.Binary value);
    partial void Oncom_imgChanged();
    partial void Onbeb_idChanging(System.Nullable<int> value);
    partial void Onbeb_idChanged();
    partial void Onsnac_idChanging(System.Nullable<int> value);
    partial void Onsnac_idChanged();
    partial void Onsnac_iestadoChanging(System.Nullable<char> value);
    partial void Onsnac_iestadoChanged();
    #endregion
		
		public tbl_Combo()
		{
			this._tbl_Factura = new EntitySet<tbl_Factura>(new Action<tbl_Factura>(this.attach_tbl_Factura), new Action<tbl_Factura>(this.detach_tbl_Factura));
			this._tbl_Bebida = default(EntityRef<tbl_Bebida>);
			this._tbl_Sanck = default(EntityRef<tbl_Sanck>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int com_id
		{
			get
			{
				return this._com_id;
			}
			set
			{
				if ((this._com_id != value))
				{
					this.Oncom_idChanging(value);
					this.SendPropertyChanging();
					this._com_id = value;
					this.SendPropertyChanged("com_id");
					this.Oncom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_nombre", DbType="VarChar(100)")]
		public string com_nombre
		{
			get
			{
				return this._com_nombre;
			}
			set
			{
				if ((this._com_nombre != value))
				{
					this.Oncom_nombreChanging(value);
					this.SendPropertyChanging();
					this._com_nombre = value;
					this.SendPropertyChanged("com_nombre");
					this.Oncom_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_precio", DbType="Real")]
		public System.Nullable<float> com_precio
		{
			get
			{
				return this._com_precio;
			}
			set
			{
				if ((this._com_precio != value))
				{
					this.Oncom_precioChanging(value);
					this.SendPropertyChanging();
					this._com_precio = value;
					this.SendPropertyChanged("com_precio");
					this.Oncom_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary com_img
		{
			get
			{
				return this._com_img;
			}
			set
			{
				if ((this._com_img != value))
				{
					this.Oncom_imgChanging(value);
					this.SendPropertyChanging();
					this._com_img = value;
					this.SendPropertyChanged("com_img");
					this.Oncom_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_beb_id", DbType="Int")]
		public System.Nullable<int> beb_id
		{
			get
			{
				return this._beb_id;
			}
			set
			{
				if ((this._beb_id != value))
				{
					if (this._tbl_Bebida.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onbeb_idChanging(value);
					this.SendPropertyChanging();
					this._beb_id = value;
					this.SendPropertyChanged("beb_id");
					this.Onbeb_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_id", DbType="Int")]
		public System.Nullable<int> snac_id
		{
			get
			{
				return this._snac_id;
			}
			set
			{
				if ((this._snac_id != value))
				{
					if (this._tbl_Sanck.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsnac_idChanging(value);
					this.SendPropertyChanging();
					this._snac_id = value;
					this.SendPropertyChanged("snac_id");
					this.Onsnac_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_iestado", DbType="Char(1)")]
		public System.Nullable<char> snac_iestado
		{
			get
			{
				return this._snac_iestado;
			}
			set
			{
				if ((this._snac_iestado != value))
				{
					this.Onsnac_iestadoChanging(value);
					this.SendPropertyChanging();
					this._snac_iestado = value;
					this.SendPropertyChanged("snac_iestado");
					this.Onsnac_iestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Combo_tbl_Factura", Storage="_tbl_Factura", ThisKey="com_id", OtherKey="com_id")]
		public EntitySet<tbl_Factura> tbl_Factura
		{
			get
			{
				return this._tbl_Factura;
			}
			set
			{
				this._tbl_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Bebida_tbl_Combo", Storage="_tbl_Bebida", ThisKey="beb_id", OtherKey="beb_id", IsForeignKey=true)]
		public tbl_Bebida tbl_Bebida
		{
			get
			{
				return this._tbl_Bebida.Entity;
			}
			set
			{
				tbl_Bebida previousValue = this._tbl_Bebida.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Bebida.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Bebida.Entity = null;
						previousValue.tbl_Combo.Remove(this);
					}
					this._tbl_Bebida.Entity = value;
					if ((value != null))
					{
						value.tbl_Combo.Add(this);
						this._beb_id = value.beb_id;
					}
					else
					{
						this._beb_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Bebida");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Sanck_tbl_Combo", Storage="_tbl_Sanck", ThisKey="snac_id", OtherKey="snac_id", IsForeignKey=true)]
		public tbl_Sanck tbl_Sanck
		{
			get
			{
				return this._tbl_Sanck.Entity;
			}
			set
			{
				tbl_Sanck previousValue = this._tbl_Sanck.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Sanck.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Sanck.Entity = null;
						previousValue.tbl_Combo.Remove(this);
					}
					this._tbl_Sanck.Entity = value;
					if ((value != null))
					{
						value.tbl_Combo.Add(this);
						this._snac_id = value.snac_id;
					}
					else
					{
						this._snac_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Sanck");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Combo = this;
		}
		
		private void detach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Combo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Factura")]
	public partial class tbl_Factura : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fact_id;
		
		private System.Nullable<System.DateTime> _fac_fecha;
		
		private System.Nullable<int> _fun_id;
		
		private System.Nullable<int> _per_id;
		
		private System.Nullable<int> _com_id;
		
		private EntityRef<tbl_Combo> _tbl_Combo;
		
		private EntityRef<tbl_Funcion> _tbl_Funcion;
		
		private EntityRef<tbl_Persona> _tbl_Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfact_idChanging(int value);
    partial void Onfact_idChanged();
    partial void Onfac_fechaChanging(System.Nullable<System.DateTime> value);
    partial void Onfac_fechaChanged();
    partial void Onfun_idChanging(System.Nullable<int> value);
    partial void Onfun_idChanged();
    partial void Onper_idChanging(System.Nullable<int> value);
    partial void Onper_idChanged();
    partial void Oncom_idChanging(System.Nullable<int> value);
    partial void Oncom_idChanged();
    #endregion
		
		public tbl_Factura()
		{
			this._tbl_Combo = default(EntityRef<tbl_Combo>);
			this._tbl_Funcion = default(EntityRef<tbl_Funcion>);
			this._tbl_Persona = default(EntityRef<tbl_Persona>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fact_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fact_id
		{
			get
			{
				return this._fact_id;
			}
			set
			{
				if ((this._fact_id != value))
				{
					this.Onfact_idChanging(value);
					this.SendPropertyChanging();
					this._fact_id = value;
					this.SendPropertyChanged("fact_id");
					this.Onfact_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fac_fecha", DbType="Date")]
		public System.Nullable<System.DateTime> fac_fecha
		{
			get
			{
				return this._fac_fecha;
			}
			set
			{
				if ((this._fac_fecha != value))
				{
					this.Onfac_fechaChanging(value);
					this.SendPropertyChanging();
					this._fac_fecha = value;
					this.SendPropertyChanged("fac_fecha");
					this.Onfac_fechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_id", DbType="Int")]
		public System.Nullable<int> fun_id
		{
			get
			{
				return this._fun_id;
			}
			set
			{
				if ((this._fun_id != value))
				{
					if (this._tbl_Funcion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfun_idChanging(value);
					this.SendPropertyChanging();
					this._fun_id = value;
					this.SendPropertyChanged("fun_id");
					this.Onfun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int")]
		public System.Nullable<int> per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					if (this._tbl_Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_com_id", DbType="Int")]
		public System.Nullable<int> com_id
		{
			get
			{
				return this._com_id;
			}
			set
			{
				if ((this._com_id != value))
				{
					if (this._tbl_Combo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncom_idChanging(value);
					this.SendPropertyChanging();
					this._com_id = value;
					this.SendPropertyChanged("com_id");
					this.Oncom_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Combo_tbl_Factura", Storage="_tbl_Combo", ThisKey="com_id", OtherKey="com_id", IsForeignKey=true)]
		public tbl_Combo tbl_Combo
		{
			get
			{
				return this._tbl_Combo.Entity;
			}
			set
			{
				tbl_Combo previousValue = this._tbl_Combo.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Combo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Combo.Entity = null;
						previousValue.tbl_Factura.Remove(this);
					}
					this._tbl_Combo.Entity = value;
					if ((value != null))
					{
						value.tbl_Factura.Add(this);
						this._com_id = value.com_id;
					}
					else
					{
						this._com_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Combo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Funcion_tbl_Factura", Storage="_tbl_Funcion", ThisKey="fun_id", OtherKey="fun_id", IsForeignKey=true)]
		public tbl_Funcion tbl_Funcion
		{
			get
			{
				return this._tbl_Funcion.Entity;
			}
			set
			{
				tbl_Funcion previousValue = this._tbl_Funcion.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Funcion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Funcion.Entity = null;
						previousValue.tbl_Factura.Remove(this);
					}
					this._tbl_Funcion.Entity = value;
					if ((value != null))
					{
						value.tbl_Factura.Add(this);
						this._fun_id = value.fun_id;
					}
					else
					{
						this._fun_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Funcion");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Persona_tbl_Factura", Storage="_tbl_Persona", ThisKey="per_id", OtherKey="per_id", IsForeignKey=true)]
		public tbl_Persona tbl_Persona
		{
			get
			{
				return this._tbl_Persona.Entity;
			}
			set
			{
				tbl_Persona previousValue = this._tbl_Persona.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Persona.Entity = null;
						previousValue.tbl_Factura.Remove(this);
					}
					this._tbl_Persona.Entity = value;
					if ((value != null))
					{
						value.tbl_Factura.Add(this);
						this._per_id = value.per_id;
					}
					else
					{
						this._per_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Persona");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Funcion")]
	public partial class tbl_Funcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _fun_id;
		
		private string _fun_descripcion;
		
		private System.Nullable<int> _sal_id;
		
		private System.Nullable<int> _hor_id;
		
		private System.Nullable<int> _pel_id;
		
		private System.Nullable<char> _fun_estado;
		
		private EntitySet<tbl_Factura> _tbl_Factura;
		
		private EntityRef<tbl_Hora> _tbl_Hora;
		
		private EntityRef<tbl_Pelicula> _tbl_Pelicula;
		
		private EntityRef<tbl_Sala> _tbl_Sala;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onfun_idChanging(int value);
    partial void Onfun_idChanged();
    partial void Onfun_descripcionChanging(string value);
    partial void Onfun_descripcionChanged();
    partial void Onsal_idChanging(System.Nullable<int> value);
    partial void Onsal_idChanged();
    partial void Onhor_idChanging(System.Nullable<int> value);
    partial void Onhor_idChanged();
    partial void Onpel_idChanging(System.Nullable<int> value);
    partial void Onpel_idChanged();
    partial void Onfun_estadoChanging(System.Nullable<char> value);
    partial void Onfun_estadoChanged();
    #endregion
		
		public tbl_Funcion()
		{
			this._tbl_Factura = new EntitySet<tbl_Factura>(new Action<tbl_Factura>(this.attach_tbl_Factura), new Action<tbl_Factura>(this.detach_tbl_Factura));
			this._tbl_Hora = default(EntityRef<tbl_Hora>);
			this._tbl_Pelicula = default(EntityRef<tbl_Pelicula>);
			this._tbl_Sala = default(EntityRef<tbl_Sala>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int fun_id
		{
			get
			{
				return this._fun_id;
			}
			set
			{
				if ((this._fun_id != value))
				{
					this.Onfun_idChanging(value);
					this.SendPropertyChanging();
					this._fun_id = value;
					this.SendPropertyChanged("fun_id");
					this.Onfun_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_descripcion", DbType="VarChar(100)")]
		public string fun_descripcion
		{
			get
			{
				return this._fun_descripcion;
			}
			set
			{
				if ((this._fun_descripcion != value))
				{
					this.Onfun_descripcionChanging(value);
					this.SendPropertyChanging();
					this._fun_descripcion = value;
					this.SendPropertyChanged("fun_descripcion");
					this.Onfun_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sal_id", DbType="Int")]
		public System.Nullable<int> sal_id
		{
			get
			{
				return this._sal_id;
			}
			set
			{
				if ((this._sal_id != value))
				{
					if (this._tbl_Sala.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onsal_idChanging(value);
					this.SendPropertyChanging();
					this._sal_id = value;
					this.SendPropertyChanged("sal_id");
					this.Onsal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hor_id", DbType="Int")]
		public System.Nullable<int> hor_id
		{
			get
			{
				return this._hor_id;
			}
			set
			{
				if ((this._hor_id != value))
				{
					if (this._tbl_Hora.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhor_idChanging(value);
					this.SendPropertyChanging();
					this._hor_id = value;
					this.SendPropertyChanged("hor_id");
					this.Onhor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_id", DbType="Int")]
		public System.Nullable<int> pel_id
		{
			get
			{
				return this._pel_id;
			}
			set
			{
				if ((this._pel_id != value))
				{
					if (this._tbl_Pelicula.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpel_idChanging(value);
					this.SendPropertyChanging();
					this._pel_id = value;
					this.SendPropertyChanged("pel_id");
					this.Onpel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fun_estado", DbType="Char(1)")]
		public System.Nullable<char> fun_estado
		{
			get
			{
				return this._fun_estado;
			}
			set
			{
				if ((this._fun_estado != value))
				{
					this.Onfun_estadoChanging(value);
					this.SendPropertyChanging();
					this._fun_estado = value;
					this.SendPropertyChanged("fun_estado");
					this.Onfun_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Funcion_tbl_Factura", Storage="_tbl_Factura", ThisKey="fun_id", OtherKey="fun_id")]
		public EntitySet<tbl_Factura> tbl_Factura
		{
			get
			{
				return this._tbl_Factura;
			}
			set
			{
				this._tbl_Factura.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hora_tbl_Funcion", Storage="_tbl_Hora", ThisKey="hor_id", OtherKey="hor_id", IsForeignKey=true)]
		public tbl_Hora tbl_Hora
		{
			get
			{
				return this._tbl_Hora.Entity;
			}
			set
			{
				tbl_Hora previousValue = this._tbl_Hora.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Hora.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Hora.Entity = null;
						previousValue.tbl_Funcion.Remove(this);
					}
					this._tbl_Hora.Entity = value;
					if ((value != null))
					{
						value.tbl_Funcion.Add(this);
						this._hor_id = value.hor_id;
					}
					else
					{
						this._hor_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Hora");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Pelicula_tbl_Funcion", Storage="_tbl_Pelicula", ThisKey="pel_id", OtherKey="pel_id", IsForeignKey=true)]
		public tbl_Pelicula tbl_Pelicula
		{
			get
			{
				return this._tbl_Pelicula.Entity;
			}
			set
			{
				tbl_Pelicula previousValue = this._tbl_Pelicula.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Pelicula.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Pelicula.Entity = null;
						previousValue.tbl_Funcion.Remove(this);
					}
					this._tbl_Pelicula.Entity = value;
					if ((value != null))
					{
						value.tbl_Funcion.Add(this);
						this._pel_id = value.pel_id;
					}
					else
					{
						this._pel_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Pelicula");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Sala_tbl_Funcion", Storage="_tbl_Sala", ThisKey="sal_id", OtherKey="sal_id", IsForeignKey=true)]
		public tbl_Sala tbl_Sala
		{
			get
			{
				return this._tbl_Sala.Entity;
			}
			set
			{
				tbl_Sala previousValue = this._tbl_Sala.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Sala.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Sala.Entity = null;
						previousValue.tbl_Funcion.Remove(this);
					}
					this._tbl_Sala.Entity = value;
					if ((value != null))
					{
						value.tbl_Funcion.Add(this);
						this._sal_id = value.sal_id;
					}
					else
					{
						this._sal_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Sala");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Funcion = this;
		}
		
		private void detach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Funcion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Genero")]
	public partial class tbl_Genero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gen_id;
		
		private string _gen_descripcion;
		
		private System.Nullable<char> _gen_estado;
		
		private EntitySet<tbl_Pelicula> _tbl_Pelicula;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongen_idChanging(int value);
    partial void Ongen_idChanged();
    partial void Ongen_descripcionChanging(string value);
    partial void Ongen_descripcionChanged();
    partial void Ongen_estadoChanging(System.Nullable<char> value);
    partial void Ongen_estadoChanged();
    #endregion
		
		public tbl_Genero()
		{
			this._tbl_Pelicula = new EntitySet<tbl_Pelicula>(new Action<tbl_Pelicula>(this.attach_tbl_Pelicula), new Action<tbl_Pelicula>(this.detach_tbl_Pelicula));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gen_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int gen_id
		{
			get
			{
				return this._gen_id;
			}
			set
			{
				if ((this._gen_id != value))
				{
					this.Ongen_idChanging(value);
					this.SendPropertyChanging();
					this._gen_id = value;
					this.SendPropertyChanged("gen_id");
					this.Ongen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gen_descripcion", DbType="VarChar(100)")]
		public string gen_descripcion
		{
			get
			{
				return this._gen_descripcion;
			}
			set
			{
				if ((this._gen_descripcion != value))
				{
					this.Ongen_descripcionChanging(value);
					this.SendPropertyChanging();
					this._gen_descripcion = value;
					this.SendPropertyChanged("gen_descripcion");
					this.Ongen_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gen_estado", DbType="Char(1)")]
		public System.Nullable<char> gen_estado
		{
			get
			{
				return this._gen_estado;
			}
			set
			{
				if ((this._gen_estado != value))
				{
					this.Ongen_estadoChanging(value);
					this.SendPropertyChanging();
					this._gen_estado = value;
					this.SendPropertyChanged("gen_estado");
					this.Ongen_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Genero_tbl_Pelicula", Storage="_tbl_Pelicula", ThisKey="gen_id", OtherKey="gen_id")]
		public EntitySet<tbl_Pelicula> tbl_Pelicula
		{
			get
			{
				return this._tbl_Pelicula;
			}
			set
			{
				this._tbl_Pelicula.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Pelicula(tbl_Pelicula entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Genero = this;
		}
		
		private void detach_tbl_Pelicula(tbl_Pelicula entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Genero = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Hora")]
	public partial class tbl_Hora : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hor_id;
		
		private string _hor_descripcion;
		
		private System.Nullable<char> _hor_estado;
		
		private EntitySet<tbl_Funcion> _tbl_Funcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhor_idChanging(int value);
    partial void Onhor_idChanged();
    partial void Onhor_descripcionChanging(string value);
    partial void Onhor_descripcionChanged();
    partial void Onhor_estadoChanging(System.Nullable<char> value);
    partial void Onhor_estadoChanged();
    #endregion
		
		public tbl_Hora()
		{
			this._tbl_Funcion = new EntitySet<tbl_Funcion>(new Action<tbl_Funcion>(this.attach_tbl_Funcion), new Action<tbl_Funcion>(this.detach_tbl_Funcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hor_id
		{
			get
			{
				return this._hor_id;
			}
			set
			{
				if ((this._hor_id != value))
				{
					this.Onhor_idChanging(value);
					this.SendPropertyChanging();
					this._hor_id = value;
					this.SendPropertyChanged("hor_id");
					this.Onhor_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hor_descripcion", DbType="VarChar(100)")]
		public string hor_descripcion
		{
			get
			{
				return this._hor_descripcion;
			}
			set
			{
				if ((this._hor_descripcion != value))
				{
					this.Onhor_descripcionChanging(value);
					this.SendPropertyChanging();
					this._hor_descripcion = value;
					this.SendPropertyChanged("hor_descripcion");
					this.Onhor_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hor_estado", DbType="Char(1)")]
		public System.Nullable<char> hor_estado
		{
			get
			{
				return this._hor_estado;
			}
			set
			{
				if ((this._hor_estado != value))
				{
					this.Onhor_estadoChanging(value);
					this.SendPropertyChanging();
					this._hor_estado = value;
					this.SendPropertyChanged("hor_estado");
					this.Onhor_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Hora_tbl_Funcion", Storage="_tbl_Funcion", ThisKey="hor_id", OtherKey="hor_id")]
		public EntitySet<tbl_Funcion> tbl_Funcion
		{
			get
			{
				return this._tbl_Funcion;
			}
			set
			{
				this._tbl_Funcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hora = this;
		}
		
		private void detach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Hora = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Pelicula")]
	public partial class tbl_Pelicula : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pel_id;
		
		private string _pel_Titulo;
		
		private string _pel_Idioma;
		
		private System.Nullable<int> _gen_id;
		
		private System.Nullable<char> _per_estado;
		
		private System.Data.Linq.Binary _pel_img;
		
		private string _pel_sinopsis;
		
		private string _pel_url;
		
		private EntitySet<tbl_Funcion> _tbl_Funcion;
		
		private EntityRef<tbl_Genero> _tbl_Genero;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpel_idChanging(int value);
    partial void Onpel_idChanged();
    partial void Onpel_TituloChanging(string value);
    partial void Onpel_TituloChanged();
    partial void Onpel_IdiomaChanging(string value);
    partial void Onpel_IdiomaChanged();
    partial void Ongen_idChanging(System.Nullable<int> value);
    partial void Ongen_idChanged();
    partial void Onper_estadoChanging(System.Nullable<char> value);
    partial void Onper_estadoChanged();
    partial void Onpel_imgChanging(System.Data.Linq.Binary value);
    partial void Onpel_imgChanged();
    partial void Onpel_sinopsisChanging(string value);
    partial void Onpel_sinopsisChanged();
    partial void Onpel_urlChanging(string value);
    partial void Onpel_urlChanged();
    #endregion
		
		public tbl_Pelicula()
		{
			this._tbl_Funcion = new EntitySet<tbl_Funcion>(new Action<tbl_Funcion>(this.attach_tbl_Funcion), new Action<tbl_Funcion>(this.detach_tbl_Funcion));
			this._tbl_Genero = default(EntityRef<tbl_Genero>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pel_id
		{
			get
			{
				return this._pel_id;
			}
			set
			{
				if ((this._pel_id != value))
				{
					this.Onpel_idChanging(value);
					this.SendPropertyChanging();
					this._pel_id = value;
					this.SendPropertyChanged("pel_id");
					this.Onpel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_Titulo", DbType="VarChar(100)")]
		public string pel_Titulo
		{
			get
			{
				return this._pel_Titulo;
			}
			set
			{
				if ((this._pel_Titulo != value))
				{
					this.Onpel_TituloChanging(value);
					this.SendPropertyChanging();
					this._pel_Titulo = value;
					this.SendPropertyChanged("pel_Titulo");
					this.Onpel_TituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_Idioma", DbType="VarChar(100)")]
		public string pel_Idioma
		{
			get
			{
				return this._pel_Idioma;
			}
			set
			{
				if ((this._pel_Idioma != value))
				{
					this.Onpel_IdiomaChanging(value);
					this.SendPropertyChanging();
					this._pel_Idioma = value;
					this.SendPropertyChanged("pel_Idioma");
					this.Onpel_IdiomaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gen_id", DbType="Int")]
		public System.Nullable<int> gen_id
		{
			get
			{
				return this._gen_id;
			}
			set
			{
				if ((this._gen_id != value))
				{
					if (this._tbl_Genero.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongen_idChanging(value);
					this.SendPropertyChanging();
					this._gen_id = value;
					this.SendPropertyChanged("gen_id");
					this.Ongen_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_estado", DbType="Char(1)")]
		public System.Nullable<char> per_estado
		{
			get
			{
				return this._per_estado;
			}
			set
			{
				if ((this._per_estado != value))
				{
					this.Onper_estadoChanging(value);
					this.SendPropertyChanging();
					this._per_estado = value;
					this.SendPropertyChanged("per_estado");
					this.Onper_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary pel_img
		{
			get
			{
				return this._pel_img;
			}
			set
			{
				if ((this._pel_img != value))
				{
					this.Onpel_imgChanging(value);
					this.SendPropertyChanging();
					this._pel_img = value;
					this.SendPropertyChanged("pel_img");
					this.Onpel_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_sinopsis", DbType="VarChar(100)")]
		public string pel_sinopsis
		{
			get
			{
				return this._pel_sinopsis;
			}
			set
			{
				if ((this._pel_sinopsis != value))
				{
					this.Onpel_sinopsisChanging(value);
					this.SendPropertyChanging();
					this._pel_sinopsis = value;
					this.SendPropertyChanged("pel_sinopsis");
					this.Onpel_sinopsisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pel_url", DbType="VarChar(100)")]
		public string pel_url
		{
			get
			{
				return this._pel_url;
			}
			set
			{
				if ((this._pel_url != value))
				{
					this.Onpel_urlChanging(value);
					this.SendPropertyChanging();
					this._pel_url = value;
					this.SendPropertyChanged("pel_url");
					this.Onpel_urlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Pelicula_tbl_Funcion", Storage="_tbl_Funcion", ThisKey="pel_id", OtherKey="pel_id")]
		public EntitySet<tbl_Funcion> tbl_Funcion
		{
			get
			{
				return this._tbl_Funcion;
			}
			set
			{
				this._tbl_Funcion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Genero_tbl_Pelicula", Storage="_tbl_Genero", ThisKey="gen_id", OtherKey="gen_id", IsForeignKey=true)]
		public tbl_Genero tbl_Genero
		{
			get
			{
				return this._tbl_Genero.Entity;
			}
			set
			{
				tbl_Genero previousValue = this._tbl_Genero.Entity;
				if (((previousValue != value) 
							|| (this._tbl_Genero.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbl_Genero.Entity = null;
						previousValue.tbl_Pelicula.Remove(this);
					}
					this._tbl_Genero.Entity = value;
					if ((value != null))
					{
						value.tbl_Pelicula.Add(this);
						this._gen_id = value.gen_id;
					}
					else
					{
						this._gen_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("tbl_Genero");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Pelicula = this;
		}
		
		private void detach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Pelicula = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Persona")]
	public partial class tbl_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_id;
		
		private string _per_nombre;
		
		private string _per_apellido;
		
		private string _per_cedula;
		
		private string _per_direccion;
		
		private System.Nullable<char> _per_estado;
		
		private EntitySet<tbl_Usuario> _tbl_Usuario;
		
		private EntitySet<tbl_Factura> _tbl_Factura;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_idChanging(int value);
    partial void Onper_idChanged();
    partial void Onper_nombreChanging(string value);
    partial void Onper_nombreChanged();
    partial void Onper_apellidoChanging(string value);
    partial void Onper_apellidoChanged();
    partial void Onper_cedulaChanging(string value);
    partial void Onper_cedulaChanged();
    partial void Onper_direccionChanging(string value);
    partial void Onper_direccionChanged();
    partial void Onper_estadoChanging(System.Nullable<char> value);
    partial void Onper_estadoChanged();
    #endregion
		
		public tbl_Persona()
		{
			this._tbl_Usuario = new EntitySet<tbl_Usuario>(new Action<tbl_Usuario>(this.attach_tbl_Usuario), new Action<tbl_Usuario>(this.detach_tbl_Usuario));
			this._tbl_Factura = new EntitySet<tbl_Factura>(new Action<tbl_Factura>(this.attach_tbl_Factura), new Action<tbl_Factura>(this.detach_tbl_Factura));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="VarChar(100)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this.Onper_nombreChanging(value);
					this.SendPropertyChanging();
					this._per_nombre = value;
					this.SendPropertyChanged("per_nombre");
					this.Onper_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellido", DbType="VarChar(100)")]
		public string per_apellido
		{
			get
			{
				return this._per_apellido;
			}
			set
			{
				if ((this._per_apellido != value))
				{
					this.Onper_apellidoChanging(value);
					this.SendPropertyChanging();
					this._per_apellido = value;
					this.SendPropertyChanged("per_apellido");
					this.Onper_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_cedula", DbType="VarChar(100)")]
		public string per_cedula
		{
			get
			{
				return this._per_cedula;
			}
			set
			{
				if ((this._per_cedula != value))
				{
					this.Onper_cedulaChanging(value);
					this.SendPropertyChanging();
					this._per_cedula = value;
					this.SendPropertyChanged("per_cedula");
					this.Onper_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="VarChar(100)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this.Onper_direccionChanging(value);
					this.SendPropertyChanging();
					this._per_direccion = value;
					this.SendPropertyChanged("per_direccion");
					this.Onper_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_estado", DbType="Char(1)")]
		public System.Nullable<char> per_estado
		{
			get
			{
				return this._per_estado;
			}
			set
			{
				if ((this._per_estado != value))
				{
					this.Onper_estadoChanging(value);
					this.SendPropertyChanging();
					this._per_estado = value;
					this.SendPropertyChanged("per_estado");
					this.Onper_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Persona_tbl_Usuario", Storage="_tbl_Usuario", ThisKey="per_id", OtherKey="per_id")]
		public EntitySet<tbl_Usuario> tbl_Usuario
		{
			get
			{
				return this._tbl_Usuario;
			}
			set
			{
				this._tbl_Usuario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Persona_tbl_Factura", Storage="_tbl_Factura", ThisKey="per_id", OtherKey="per_id")]
		public EntitySet<tbl_Factura> tbl_Factura
		{
			get
			{
				return this._tbl_Factura;
			}
			set
			{
				this._tbl_Factura.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Usuario(tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Persona = this;
		}
		
		private void detach_tbl_Usuario(tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Persona = null;
		}
		
		private void attach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Persona = this;
		}
		
		private void detach_tbl_Factura(tbl_Factura entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Rol")]
	public partial class tbl_Rol : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _rol_id;
		
		private string _rol_descripcion;
		
		private System.Nullable<char> _rol_estado;
		
		private EntitySet<tbl_Usuario> _tbl_Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onrol_idChanging(int value);
    partial void Onrol_idChanged();
    partial void Onrol_descripcionChanging(string value);
    partial void Onrol_descripcionChanged();
    partial void Onrol_estadoChanging(System.Nullable<char> value);
    partial void Onrol_estadoChanged();
    #endregion
		
		public tbl_Rol()
		{
			this._tbl_Usuario = new EntitySet<tbl_Usuario>(new Action<tbl_Usuario>(this.attach_tbl_Usuario), new Action<tbl_Usuario>(this.detach_tbl_Usuario));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int rol_id
		{
			get
			{
				return this._rol_id;
			}
			set
			{
				if ((this._rol_id != value))
				{
					this.Onrol_idChanging(value);
					this.SendPropertyChanging();
					this._rol_id = value;
					this.SendPropertyChanged("rol_id");
					this.Onrol_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_descripcion", DbType="VarChar(100)")]
		public string rol_descripcion
		{
			get
			{
				return this._rol_descripcion;
			}
			set
			{
				if ((this._rol_descripcion != value))
				{
					this.Onrol_descripcionChanging(value);
					this.SendPropertyChanging();
					this._rol_descripcion = value;
					this.SendPropertyChanged("rol_descripcion");
					this.Onrol_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rol_estado", DbType="Char(1)")]
		public System.Nullable<char> rol_estado
		{
			get
			{
				return this._rol_estado;
			}
			set
			{
				if ((this._rol_estado != value))
				{
					this.Onrol_estadoChanging(value);
					this.SendPropertyChanging();
					this._rol_estado = value;
					this.SendPropertyChanged("rol_estado");
					this.Onrol_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Rol_tbl_Usuario", Storage="_tbl_Usuario", ThisKey="rol_id", OtherKey="rol_id")]
		public EntitySet<tbl_Usuario> tbl_Usuario
		{
			get
			{
				return this._tbl_Usuario;
			}
			set
			{
				this._tbl_Usuario.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Usuario(tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Rol = this;
		}
		
		private void detach_tbl_Usuario(tbl_Usuario entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Rol = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Sala")]
	public partial class tbl_Sala : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sal_id;
		
		private string _sal_descripcion;
		
		private System.Nullable<char> _sal_estado;
		
		private EntitySet<tbl_Funcion> _tbl_Funcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsal_idChanging(int value);
    partial void Onsal_idChanged();
    partial void Onsal_descripcionChanging(string value);
    partial void Onsal_descripcionChanged();
    partial void Onsal_estadoChanging(System.Nullable<char> value);
    partial void Onsal_estadoChanged();
    #endregion
		
		public tbl_Sala()
		{
			this._tbl_Funcion = new EntitySet<tbl_Funcion>(new Action<tbl_Funcion>(this.attach_tbl_Funcion), new Action<tbl_Funcion>(this.detach_tbl_Funcion));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sal_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sal_id
		{
			get
			{
				return this._sal_id;
			}
			set
			{
				if ((this._sal_id != value))
				{
					this.Onsal_idChanging(value);
					this.SendPropertyChanging();
					this._sal_id = value;
					this.SendPropertyChanged("sal_id");
					this.Onsal_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sal_descripcion", DbType="VarChar(100)")]
		public string sal_descripcion
		{
			get
			{
				return this._sal_descripcion;
			}
			set
			{
				if ((this._sal_descripcion != value))
				{
					this.Onsal_descripcionChanging(value);
					this.SendPropertyChanging();
					this._sal_descripcion = value;
					this.SendPropertyChanged("sal_descripcion");
					this.Onsal_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sal_estado", DbType="Char(1)")]
		public System.Nullable<char> sal_estado
		{
			get
			{
				return this._sal_estado;
			}
			set
			{
				if ((this._sal_estado != value))
				{
					this.Onsal_estadoChanging(value);
					this.SendPropertyChanging();
					this._sal_estado = value;
					this.SendPropertyChanged("sal_estado");
					this.Onsal_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Sala_tbl_Funcion", Storage="_tbl_Funcion", ThisKey="sal_id", OtherKey="sal_id")]
		public EntitySet<tbl_Funcion> tbl_Funcion
		{
			get
			{
				return this._tbl_Funcion;
			}
			set
			{
				this._tbl_Funcion.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Sala = this;
		}
		
		private void detach_tbl_Funcion(tbl_Funcion entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Sala = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_Sanck")]
	public partial class tbl_Sanck : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _snac_id;
		
		private string _snac_nombre;
		
		private System.Nullable<float> _snac_precio;
		
		private System.Nullable<int> _snac_stock;
		
		private System.Data.Linq.Binary _snac_img;
		
		private System.Nullable<char> _snac_estado;
		
		private EntitySet<tbl_Combo> _tbl_Combo;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsnac_idChanging(int value);
    partial void Onsnac_idChanged();
    partial void Onsnac_nombreChanging(string value);
    partial void Onsnac_nombreChanged();
    partial void Onsnac_precioChanging(System.Nullable<float> value);
    partial void Onsnac_precioChanged();
    partial void Onsnac_stockChanging(System.Nullable<int> value);
    partial void Onsnac_stockChanged();
    partial void Onsnac_imgChanging(System.Data.Linq.Binary value);
    partial void Onsnac_imgChanged();
    partial void Onsnac_estadoChanging(System.Nullable<char> value);
    partial void Onsnac_estadoChanged();
    #endregion
		
		public tbl_Sanck()
		{
			this._tbl_Combo = new EntitySet<tbl_Combo>(new Action<tbl_Combo>(this.attach_tbl_Combo), new Action<tbl_Combo>(this.detach_tbl_Combo));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int snac_id
		{
			get
			{
				return this._snac_id;
			}
			set
			{
				if ((this._snac_id != value))
				{
					this.Onsnac_idChanging(value);
					this.SendPropertyChanging();
					this._snac_id = value;
					this.SendPropertyChanged("snac_id");
					this.Onsnac_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_nombre", DbType="VarChar(100)")]
		public string snac_nombre
		{
			get
			{
				return this._snac_nombre;
			}
			set
			{
				if ((this._snac_nombre != value))
				{
					this.Onsnac_nombreChanging(value);
					this.SendPropertyChanging();
					this._snac_nombre = value;
					this.SendPropertyChanged("snac_nombre");
					this.Onsnac_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_precio", DbType="Real")]
		public System.Nullable<float> snac_precio
		{
			get
			{
				return this._snac_precio;
			}
			set
			{
				if ((this._snac_precio != value))
				{
					this.Onsnac_precioChanging(value);
					this.SendPropertyChanging();
					this._snac_precio = value;
					this.SendPropertyChanged("snac_precio");
					this.Onsnac_precioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_stock", DbType="Int")]
		public System.Nullable<int> snac_stock
		{
			get
			{
				return this._snac_stock;
			}
			set
			{
				if ((this._snac_stock != value))
				{
					this.Onsnac_stockChanging(value);
					this.SendPropertyChanging();
					this._snac_stock = value;
					this.SendPropertyChanged("snac_stock");
					this.Onsnac_stockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_img", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary snac_img
		{
			get
			{
				return this._snac_img;
			}
			set
			{
				if ((this._snac_img != value))
				{
					this.Onsnac_imgChanging(value);
					this.SendPropertyChanging();
					this._snac_img = value;
					this.SendPropertyChanged("snac_img");
					this.Onsnac_imgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snac_estado", DbType="Char(1)")]
		public System.Nullable<char> snac_estado
		{
			get
			{
				return this._snac_estado;
			}
			set
			{
				if ((this._snac_estado != value))
				{
					this.Onsnac_estadoChanging(value);
					this.SendPropertyChanging();
					this._snac_estado = value;
					this.SendPropertyChanged("snac_estado");
					this.Onsnac_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbl_Sanck_tbl_Combo", Storage="_tbl_Combo", ThisKey="snac_id", OtherKey="snac_id")]
		public EntitySet<tbl_Combo> tbl_Combo
		{
			get
			{
				return this._tbl_Combo;
			}
			set
			{
				this._tbl_Combo.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbl_Combo(tbl_Combo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Sanck = this;
		}
		
		private void detach_tbl_Combo(tbl_Combo entity)
		{
			this.SendPropertyChanging();
			entity.tbl_Sanck = null;
		}
	}
}
#pragma warning restore 1591
